apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
    service: productpage
spec:
  ports:
  - port: {{ .Values.productpage.port }}
    name: http
  selector:
    app: productpage