apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ingress-nginx-monitoring
  namespace: prometheus
  labels:
    release: kube-prometheus-stack
spec:
  groups:
  - name: ingress-nginx
    rules:
    - alert: NGINXConfigFailed
      annotations:
        description: bad ingress config - nginx config test failed
        summary: uninstall the latest ingress changes to allow config reloads to resume
      expr: count(nginx_ingress_controller_config_last_reload_successful{controller_class=~".*"}
        == 0) > 0
      for: 1s
      labels:
        severity: critical
    - alert: NGINXCertificateExpiry
      annotations:
        description: {{ `ssl certificate {{$labels.host}} will expire in less then a week`}}
        summary: renew expiring certificates to avoid downtime
      expr: (avg(nginx_ingress_controller_ssl_expire_time_seconds{class=~".*"}) by
        (host) - time()) < 604800
      for: 1s
      labels:
        severity: critical
    - alert: NGINXTooMany500s
      annotations:
        description: {{` Too many {{$labels.status}} on {{$labels.host}} `}}
        summary: {{` More than 5% of all requests returned {{$labels.status}}. Metadata
          -> { namespace="{{$labels.exported_namespace}}", ingress="{{$labels.ingress}}",
          method="{{$labels.method}}", path="{{$labels.path}})" } `}}
      expr: 100 * (sum by(ingress, exported_namespace, status,method,path,host) (rate(nginx_ingress_controller_requests{status=~"5.+",
        controller_class=~".*"}[5m])) / sum by(ingress, exported_namespace, status,method,path,host)
        (rate(nginx_ingress_controller_requests{controller_class=~".*"}[5m]))) > 5
      for: 1m
      labels:
        severity: error
    - alert: NGINXTooMany400s
      annotations:
        description: {{` Too many {{$labels.status}} on {{$labels.host}} `}}
        summary: {{` More than 5% of all requests returned {{$labels.status}}. Metadata
          -> { namespace="{{$labels.exported_namespace}}", ingress="{{$labels.ingress}}",
          method="{{$labels.method}}", path="{{$labels.path}})" } `}}
      expr: 100 * (sum by(ingress, exported_namespace, status,method,path,host) (rate(nginx_ingress_controller_requests{status=~"4.+",
        controller_class=~".*", host!~'grafana.*'}[5m])) / sum by(ingress, exported_namespace, status,method,path,host)
        (rate(nginx_ingress_controller_requests{controller_class=~".*", host!~"grafana.*"}[5m]))) > 5
      for: 1m
      labels:
        severity: warning
