apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-v1
  labels:
    app: details
    version: v1
spec:
  replicas: {{ .Values.details.replicas }}
  selector:
    matchLabels:
      app: details
      version: v1
  template:
    metadata:
      labels:
        app: details
        version: v1
    spec:
      serviceAccountName: bookinfo-details
      containers:
      - name: details
        image: {{ .Values.details.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.details.port }}
        readinessProbe:
          httpGet:
            path: {{ .Values.details.probePath }}
            port: {{ .Values.details.port }}
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: {{ .Values.details.probePath }}
            port: {{ .Values.details.port }}
          initialDelaySeconds: 15
          periodSeconds: 10
        securityContext:
          runAsUser: 1000