apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v2
  labels:
    app: reviews
    version: v2
spec:
  replicas: {{ .Values.reviews.replicas }}
  selector:
    matchLabels:
      app: reviews
      version: v2
  template:
    metadata:
      labels:
        app: reviews
        version: v2
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
      - name: reviews
        image: '{{ .Values.registry.base }}/{{ .Values.registry.id }}/{{ .Values.registry.folder }}/{{ .Values.reviews.image_v2 }}'
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: {{ .Values.reviews.port }}
        readinessProbe:
          httpGet:
            path: {{ .Values.reviews.probePath }}
            port: {{ .Values.reviews.port }}
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: {{ .Values.reviews.probePath }}
            port: {{ .Values.reviews.port }}
          initialDelaySeconds: 15
          periodSeconds: 10
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
        securityContext:
          runAsUser: 1000
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}