secret:
    accessKey: ENC[AES256_GCM,data:5e5GB+EI7XvIji6socwmyOCBAXwkpbc1gg==,iv:XpTtgSoyfYitpFZot5HMPj5dv3cpPLP8OjyZisom/R0=,tag:RCqetAHc8YumgdZXA4/kgQ==,type:str]
    secretKey: ENC[AES256_GCM,data:HcbrQ0oBlHAbbNNGkmiTJiuIsWRBMV3DOdckTryLE8nKyjlC5AkAow==,iv:NPwHJCpbcqurOayKAihNrxVc9XT2j8lOh/agIx7lSAA=,tag:xCfyNEgJuDje8/W6CKPLcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-04T20:29:30Z"
    mac: ENC[AES256_GCM,data:C3kC0uiYihUfoxwPtF9ac7DHS8ymYYi/XqKHudBZaBJT5MKyErUD80gDB94jwzPCWP+C3Iqn9Dqn+19XlYzmAxXZlw75thl2Sex6lXMcs041POPjza9wiFhyWThFSSMdOQZ//qeX/2H1llyXa4LjjRYRcvvPR7BMn+MhQSO+/XI=,iv:q9zYiUw59JZtJQS6tw0HiQwGxIqk9LUHDonnLUqbJ44=,tag:W7KBxBCSLlEuPTIr5DErSA==,type:str]
    pgp:
        - created_at: "2024-02-02T22:25:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA9gg0Mqtza18AQv+IpLinJX2Kshu879VxpRX/Qy+oDuz8IaEiFm4T4urfBtv
            GzifruNBIW24Gww1d9wP3D6hDdKs7gayUYUCjjECZve8DhL/VpLYKs8KOmMcFLrK
            ZZ7sVW5E95bYp9qI+SXi88/ZLerdCGgQukBQ1MK1qUthC0bOi1C+f1NNMTEpwz4b
            xLwt2XUaW5dMQYdPGT5yf7WLpKVTTBeDRwGfVxTmQ8eu3LmPMRv6/E0FL8xolumH
            29Yb9jt53O+/ViubQtB562dMOxNmjIu7Vb+QlICSlL5qxrRlw9nwFHbV4cTQGk1x
            DJFYffmcjTEqP17F3OErmQOCNyzY1RXbRJiyl0kT0y+g/VIbfEhQjdGwOrso9omS
            wECy0COBndNEQtoORTutZyyhijWevlau201c4LIInLwz2nkrMjyfNNxiAd2s0J+2
            Q2hgs/oJ4e0Fz+QxgjWUQeZdgIfs6gGbGvpAMcwb7l2x10Mielt9fgNoJ0Q0kfGi
            I606W8j2HrKF8uZN+ZD60lwBMjwFnE9UNrFcVjgrZj+3ZwD3kSpSL+GReLH3TorS
            /1ON7uAk8aCnHGlWS0mi+b+kOfItuegTTMWw7t7x7TUYdKjm59OHz+BGg6APt3VB
            y/FKluATWnXrGsYD/w==
            =Sxsx
            -----END PGP MESSAGE-----
          fp: F8A5F08C86B82A373EC6CCFEA396AE8FA14BF67E
    unencrypted_suffix: _unencrypted
    version: 3.8.1
