{
 "title": "Flask Monitoring",
 "description": "Monitor Flask application through custom StatsD metrics with Prometheus and Grafana.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(flask_info{}, app_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (request_result_total{app_name=\"$app_name\"})"
    }
   ]
  },
  {
   "title": "Requests Per Status Code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (request_result_total{app_name=\"$app_name\"}) by(response_code)",
     "legendFormat": "Code: {{response_code}}"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(request_result_total{}[1m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Requests Code by Service 1h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(request_result_total[1h])",
     "legendFormat": "{{destination_app}} | code {{response_code}} |"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(request_result_total{response_code=~\"5.*\"}[5m])) by(container) /sum(rate(request_result_total{}[5m])) by(container)",
     "legendFormat": "{{destination_app}} "
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(request_result_total{response_code=~\"2.*\"}[5m])) by(container) / sum(rate(request_result_total[5m])) by(container)",
     "legendFormat": "{{destination_app}}"
    }
   ]
  },
  {
   "title": "Request Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(nginx_ingress_controller_response_duration_seconds_bucket{}[5m])) by (le,ingress)) \n",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}