ingress:
  hostname: k8s-uptime.ru

productpage:
  port: 9080
  probePath: /health
  image: examples-bookinfo-productpage-v1:latest
  replicas: 1

reviews:
  port: 9080
  probePath: /health
  image_v1: examples-bookinfo-reviews-v1:latest
  image_v2: examples-bookinfo-reviews-v2:latest
  image_v3: examples-bookinfo-reviews-v3:latest
  replicas: 1

details:
  port: 9080
  probePath: /health
  image: examples-bookinfo-details-v1:latest
  replicas: 1

ratings:
  port: 9080
  probePath: /health
  image: examples-bookinfo-ratings-v1:latest
  replicas: 1

registry:
  base: cr.yandex
  id: crpbhbkl8qh584mutl3u
  folder: bookinfo
