ingress:
  hostname: k8s-uptime.ru

dns: 
  enabled: true

productpage:
  port: 9080
  probePath: /health
  image: examples-bookinfo-productpage-v1:v1
  replicas: 2
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "100Mi"
      cpu: "100m"

reviews:
  port: 9080
  probePath: /health
  image_v1: examples-bookinfo-reviews-v1:v1
  image_v2: examples-bookinfo-reviews-v2:v1
  image_v3: examples-bookinfo-reviews-v3:v1
  replicas: 2
  resources:
    requests:
      memory: "150Mi"
      cpu: "100m"
    limits:
      memory: "500Mi"
      cpu: "500m"

details:
  port: 9080
  probePath: /health
  image: examples-bookinfo-details-v1:v1
  replicas: 2
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "100Mi"
      cpu: "100m"

ratings:
  port: 9080
  probePath: /health
  image: examples-bookinfo-ratings-v-unhealthy:v1
  replicas: 2
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "100Mi"
      cpu: "100m"

registry:
  base: cr.yandex
  id: crpmugbv6k1atn1lldsi
