ingress:
  hostname: k8s-uptime.ru

productpage:
  port: 9080
  probePath: /health

reviews:
  port: 9080
  probePath: /health

details:
  port: 9080
  probePath: /health

ratings:
  port: 9080
  probePath: /health
